export const killerRequirements: Record<string, string> = {
  "The Trapper": "at least 1 trap grab",
  "The Wraith": "at least 1 hit after uncloak",
  "The Hillbilly": "at least 1 chainsaw hit",
  "The Nurse": "at least 1 blink attack",
  "The Shape": "not trackable",
  "The Hag": "at least 1 trap triggered",
  "The Doctor": "at least 1 shock",
  "The Huntress": "at least 1 hatchet thrown",
  "The Cannibal": "at least 1 chainsaw hit",
  "The Nightmare": "at least 1 survivor put to sleep",
  "The Pig": "at least 1 reverse bear-trap applied",
  "The Clown": "at least 1 intoxicated survivor downed",
  "The Spirit": "at least 1 survivor downed after phase walk",
  "The Legion": "at least 1 deep-wounded survivor downed",
  "The Plague": "at least 1 max sickness survivor downed",
  "The Ghost Face": "at least 1 marked survivor downed",
  "The Demogorgon": "not trackable",
  "The Oni": "at least 1 demon fury down",
  "The Deathslinger": "at least 1 speared survivor downed",
  "The Executioner": "at least 1 survivor caged",
  "The Blight": "at least 1 lethal rush hit",
  "The Twins": "at least 1 survivor downed with Victor latched on",
  "The Trickster": "at least 1 max laceration reached",
  "The Nemesis": "at least 1 contaminated survivor downed",
  "The Cenobite": "not trackable",
  "The Artist": "at least 1 survivor downed with dire crows",
  "The Onryō": "at least 1 survivor condemned",
  "The Dredge": "at least 1 survivor downed in nightfall",
  "The Mastermind": "at least 1 survivor slammed into another",
  "The Knight": "at least 1 survivor damaged while pursued by a guard",
  "The Skull Merchant": "at least 1 claw trapped survivor downed",
  "The Singularity": "at least 1 survivor hit after recent teleport",
  "The Xenomorph": "at least 1 survivor hit with a tail attack",
  "The Good Guy": "at least 1 survivor hit within 3 seconds of a scamper",
  "The Unknown": "at least 1 survivor hit with a UVX blast",
  "The Lich": "at least 1 survivor hit within 15 seconds of casting a spell",
  "The Dark Lord": "at least 1 survivor hit with hellfire",
  "The Houndmaster": "at least 1 survivor injured while detained by the dog",
  "The Ghoul": "at least 1 perfectly timed grab-attack",
  "The Animatronic": "at least 1 survivor interrupted in security office",
  "The Krasue": "at least 1 whip down",
  "The First": "at least 1 survivor damaged with vine or undergate attacks",
};
