// <auto-generated />
using System;
using DbdMatches.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbdMatches.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316204454_AddStreaks")]
    partial class AddStreaks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbdMatches.Api.Models.MatchKiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodpointsEarned")
                        .HasColumnType("integer")
                        .HasColumnName("bloodpoints_earned");

                    b.Property<string>("Killer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("killer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PowerStat1")
                        .HasColumnType("integer")
                        .HasColumnName("power_stat1");

                    b.Property<int>("PowerStat2")
                        .HasColumnType("integer")
                        .HasColumnName("power_stat2");

                    b.Property<int>("PowerStat3")
                        .HasColumnType("integer")
                        .HasColumnName("power_stat3");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("result");

                    b.Property<int>("Sacrifices")
                        .HasColumnType("integer")
                        .HasColumnName("sacrifices");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_match_killers");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_killers_public_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_match_killers_user_id");

                    b.ToTable("match_killers", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.MatchSurvivor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodpointsEarned")
                        .HasColumnType("integer")
                        .HasColumnName("bloodpoints_earned");

                    b.Property<bool>("Escaped")
                        .HasColumnType("boolean")
                        .HasColumnName("escaped");

                    b.Property<double>("GeneratorsCompleted")
                        .HasColumnType("double precision")
                        .HasColumnName("generators_completed");

                    b.Property<bool>("HatchEscape")
                        .HasColumnType("boolean")
                        .HasColumnName("hatch_escape");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("result");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_match_survivors");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_survivors_public_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_match_survivors_user_id");

                    b.ToTable("match_survivors", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.PlayerStatsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("StatName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stat_name");

                    b.Property<double>("StatValue")
                        .HasColumnType("double precision")
                        .HasColumnName("stat_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_player_stats_snapshots");

                    b.HasIndex("UserId", "StatName")
                        .IsUnique()
                        .HasDatabaseName("ix_player_stats_snapshots_user_id_stat_name");

                    b.ToTable("player_stats_snapshots", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.Streak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestKiller")
                        .HasColumnType("integer")
                        .HasColumnName("best_killer");

                    b.Property<int>("BestOverall")
                        .HasColumnType("integer")
                        .HasColumnName("best_overall");

                    b.Property<int>("BestSurvivor")
                        .HasColumnType("integer")
                        .HasColumnName("best_survivor");

                    b.Property<int>("CurrentKiller")
                        .HasColumnType("integer")
                        .HasColumnName("current_killer");

                    b.Property<int>("CurrentOverall")
                        .HasColumnType("integer")
                        .HasColumnName("current_overall");

                    b.Property<int>("CurrentSurvivor")
                        .HasColumnType("integer")
                        .HasColumnName("current_survivor");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_streaks");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_streaks_user_id");

                    b.ToTable("streaks", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.StreakKiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("best_streak");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<string>("Killer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("killer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_streak_killers");

                    b.HasIndex("UserId", "Killer")
                        .IsUnique()
                        .HasDatabaseName("ix_streak_killers_user_id_killer");

                    b.ToTable("streak_killers", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("steam_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_public_id");

                    b.HasIndex("SteamId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_steam_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_info");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("LoggedInAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_in_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LoggedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_out_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("DbdMatches.Api.Models.MatchKiller", b =>
                {
                    b.HasOne("DbdMatches.Api.Models.User", "User")
                        .WithMany("KillerMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_killers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbdMatches.Api.Models.MatchSurvivor", b =>
                {
                    b.HasOne("DbdMatches.Api.Models.User", "User")
                        .WithMany("SurvivorMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_survivors_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbdMatches.Api.Models.PlayerStatsSnapshot", b =>
                {
                    b.HasOne("DbdMatches.Api.Models.User", "User")
                        .WithMany("StatsSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_stats_snapshots_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbdMatches.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("DbdMatches.Api.Models.UserSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_sessions_session_id");

                    b.HasOne("DbdMatches.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbdMatches.Api.Models.Streak", b =>
                {
                    b.HasOne("DbdMatches.Api.Models.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("DbdMatches.Api.Models.Streak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_streaks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbdMatches.Api.Models.StreakKiller", b =>
                {
                    b.HasOne("DbdMatches.Api.Models.User", "User")
                        .WithMany("StreakKillers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_streak_killers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbdMatches.Api.Models.UserSession", b =>
                {
                    b.HasOne("DbdMatches.Api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbdMatches.Api.Models.User", b =>
                {
                    b.Navigation("KillerMatches");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");

                    b.Navigation("StatsSnapshots");

                    b.Navigation("Streak");

                    b.Navigation("StreakKillers");

                    b.Navigation("SurvivorMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
